### ISSUE TITLE
0.2.0 always returns "master"

### ISSUE THREAD

**Issue by kevinrenskers** [jonschlinkert/git-branch#1]
According to the docs usage is something like this:

```
var branch = require('git-branch');
console.log(branch);
```

This worked fine in 0.1.x but in 0.2.x `require('git-branch')` returns a function instead of the branch as a string. What's worse, is that that function always returns "master", no matter what branch I'm in.

**Comment by jonschlinkert** [comment]
strange, thanks for reporting this. when I tested it gave me the branch I was on. I'll look into it

**Comment by jonschlinkert** [comment]
Fixed in 0.3.0. Also note that the signature has changed to allow for both async and sync methods.
